"""İlk migration

Revision ID: b269f8dd9e58
Revises: 
Create Date: 2025-11-16 16:19:41.504700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b269f8dd9e58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('yemekler', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarih')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('menu_id', sa.String(length=50), nullable=False),
    sa.Column('kullanici_id', sa.String(length=50), nullable=False),
    sa.Column('yorum_metni', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kullanici_id', sa.String(length=50), nullable=False),
    sa.Column('menu_id', sa.String(length=50), nullable=False),
    sa.Column('puan', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_id', 'menu_id', name='unique_user_menu_rating')
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kullanici_id', sa.String(length=50), nullable=False),
    sa.Column('yorum_id', sa.String(length=50), nullable=False),
    sa.Column('begeni_tipi', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['yorum_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_id', 'yorum_id', name='unique_user_comment_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    op.drop_table('ratings')
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('menus')
    # ### end Alembic commands ###
